### ISSUE TITLE
FATAL EXCEPTION: Socket-Worker-Thread

### ISSUE THREAD

**Issue by surajpunemaha** [tigase/jaxmpp#4]
2020-12-02 20:26:51.289 4243-4378/com.xxxx.xxxx I/AccountCreator: Event: class tigase.jaxmpp.core.client.Connector$StateChangedHandler$StateChangedEvent
2020-12-02 20:26:51.289 4243-4378/com.xxxx.xxxx D/se.eventbus.ThreadSafeEventBus: Calling handler class class tigase.jaxmpp.core.client.JaxmppCore$5 with event class tigase.jaxmpp.core.client.Connector$StreamTerminatedHandler$StreamTerminatedEvent
2020-12-02 20:26:51.290 4243-4378/com.xxxx.xxxx D/se.eventbus.ThreadSafeEventBus: Calling handler class class tigase.jaxmpp.core.client.xmpp.modules.StreamFeaturesModule$3 with event class tigase.jaxmpp.core.client.Connector$StreamTerminatedHandler$StreamTerminatedEvent
    
    --------- beginning of crash
2020-12-02 20:26:51.291 4243-4424/com.xxxx.xxxx E/AndroidRuntime: FATAL EXCEPTION: Socket-Worker-Thread
    Process: com.xxxx.xxxx, PID: 4243
    java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
        at tigase.jaxmpp.j2se.connectors.socket.TextStreamReader.read(TextStreamReader.java:56)
        at tigase.jaxmpp.j2se.connectors.socket.Worker.run(Worker.java:113)

**Comment by surajpunemaha** [comment]
@hantu85  thank you for your reply.
We are using java 1.8.0_242 (built in with android studio) as a targetCompatibility and sourceCompatibility in android gradle. As well as  java enabled modules are  there using same 1.8 java version.
targetSdkVersion 29 for android.

**Comment by bmalkow** [comment]
I recompiled everything with Java8 (1.8.0_265) and I added cast to Buffer in problematic place.
I also reproduced your error during compilation: when I compiled code using Java 11 and then I switched sdk to 1.8.0 and tried compiling again without cleaning the project.
